apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;
            
            # Define subdominios específicos
            server_name flask.localdev.me;

            # Redirige solo las solicitudes a flask.localdev.me
            location / {
                proxy_pass http://flask-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /evento/ {
                proxy_pass http://flask-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE';
                add_header Access-Control-Allow-Headers 'Content-Type, Authorization';
            }

            # API
            location /api/ {
                proxy_pass http://flask-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE';
                add_header Access-Control-Allow-Headers 'Content-Type, Authorization';
            }
        }

        server {
            listen 80;

            # Define otro subdominio para Adminer
            server_name adminer.localdev.me;

            # Redirige solo las solicitudes a adminer.localdev.me
            location / {
                proxy_pass http://adminer-service:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

        server {
            listen 80;

            # Define otro subdominio para Gotenberg
            server_name gotenberg.localdev.me;

            # Redirige solo las solicitudes a gotenberg.localdev.me
            location / {
                proxy_pass http://gotenberg-service:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }

    }
