apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: python:latest
        env:
        - name: POSTGRES_USER
          value: as
        - name: POSTGRES_DB
          value: database
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        volumeMounts:
        - name: flask-app
          mountPath: /app
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args:
          - >
            pip install --upgrade pip &&
            pip install -r /app/requirements.txt &&
            python /app/app.py;
      volumes:
      - name: flask-app
        configMap:
          name: flask-config-map
