apiVersion: v1
kind: Service
metadata:
  name: gotenberg-service
spec:
  type: NodePort
  selector:
    app: gotenberg
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
